name: Check domains

on:
  push:
    branches: [ master ]
  #schedule:
  #  - cron:  '0 8 * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Check domain
    strategy:
      matrix:
        domain:
          - https://www.gorro.com.ar
          - https://tienda.gorro.com.ar
          - https://www.tresdoce.com.ar
          - https://www.estudiofluk.com.ar
          - https://apicedes.tresdoce.com.ar
          - https://www.estudiohamaca.com.ar
          - https://www.adipol.com.ar
          - https://www.fragrancemarket.com.ar
          - https://jenkins.tresdoce.com.ar
          - https://static-pre.tresdoce.com.ar
          - https://static.tresdoce.com.ar

    steps:
      - name: Check domain SSL and registry expire date
        id: check-domain
        uses: codex-team/action-check-domain@v1
        with:
          url: ${{ matrix.domain }}

      - run: echo 'SSL cert has ${{ steps.check-domain.outputs.ssl-expire-days-left }} days left'
        if: ${{ steps.check-domain.outputs.ssl-expire-days-left }}
